OD.UI/Controllers/OgretmenController.cs
using OD.Bll.Concrete;
using OD.Model;
using OD.UI.LogFolder;
using OD.UI.Utils;
using OD.UI.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OD.UI.Controllers
{

    public class OgretmenController : BaseController.BaseController
    {
        OgretmenRepository ogretmenrepo = new OgretmenRepository();
        OgrenciRepository ogrencirepo = new OgrenciRepository();
        DerslerRepository dersrepo = new DerslerRepository();
        AtananDerslerRepository atanandersrepo = new AtananDerslerRepository();
        DonemlerRepository donemrepo = new DonemlerRepository();
        OkulRepository okulrepo = new OkulRepository();
        DersGruplariRepository dersgruprepo = new DersGruplariRepository();
        YoklamaRepository yoklamarepo = new YoklamaRepository();
        Fonksiyon f = new Fonksiyon();

        [LogFolder.OgretmenLog]
        public ActionResult Index()
        {
            int OgretmenID = Convert.ToInt32(Session["OgretmenID"]);
            string okul = ogretmenrepo.Get(OgretmenID).Okullar.Adi;
            ViewBag.Title = okul;
            return View();
        }

        public ActionResult CikisYap()
        {
            Session.Remove("OgretmenID");
            return RedirectToAction("Index", "Home");
        }

        public JsonResult SinifSubeFiltre(int id)
        {
            Donemler donem = donemrepo.GetByFilter(a => a.AktifMi == true);
            int OgretmenID = Convert.ToInt32(Session["OgretmenID"]);
            SinifDersOgrenciListView SinifSube = new SinifDersOgrenciListView();
            SinifSube.SubeGrup = (from i in atanandersrepo.GetByFilterList(a => a.OgretmenID == OgretmenID && a.AktifMi == true && a.Sinif == id && a.DonemID == donem.DonemID).ToList()
                                  orderby i.Sinif
                                  group i by i.Sube into g
                                  select new SelectListItem
                                  {
                                      Text = g.Key.ToString().ToUpper(),
                                      Value = g.Key.ToString()
                                  }).ToList();

            return Json(SinifSube.SubeGrup, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SinifDersFiltre(int sinif, string sube)
        {
            Donemler donem = donemrepo.GetByFilter(a => a.AktifMi == true);
            int OgretmenID = Convert.ToInt32(Session["OgretmenID"]);
            SinifDersOgrenciListView SinifDers = new SinifDersOgrenciListView();
            SinifDers.DersListe = (from i in atanandersrepo.GetByFilterList(a => a.OgretmenID == OgretmenID && a.AktifMi == true && a.Sinif == sinif && a.Sube == sube && a.DonemID == donem.DonemID).ToList()
                                   orderby i.Dersler.DersAdi
                                   select new SelectListItem
                                   {
                                       Text = i.Dersler.DersAdi.ToString().ToUpper(),
                                       Value = i.DersID.ToString()
                                   }).ToList();

            return Json(SinifDers.DersListe, JsonRequestBehavior.AllowGet);
        }

        [LogFolder.OgretmenLog]
        public ActionResult YoklamaAl(int Sinif = 0, string Sube = null, int DersID = 0, int DersGrupID = 0)
        {
            int OgretmenID = Convert.ToInt32(Session["OgretmenID"]);
            SinifDersOgrenciListView model = new SinifDersOgrenciListView();
            //model.SinifGrup = (from i in atanandersrepo.GetByFilterList(a => a.OgretmenID == OgretmenID && a.AktifMi == true).ToList()
            //                   orderby i.Sinif
            //                   group i by i.Sinif into g
            //                   select new SelectListItem
            //                   {
            //                       Text = g.Key.ToString(),
            //                       Value = g.Key.ToString()
            //                   }).ToList();

            //ViewData["DersSaatleri"] = from i in dersgruprepo.GetAll()
            //                           select new SelectListItem
            //                           {
            //                               Value = i.DersGrupID.ToString(),
            //                               Text = i.DersGrupAdi
            //                           };
            Donemler d = donemrepo.GetByFilter(a => a.AktifMi == true);
            ViewData["YoklamaListe"] = yoklamarepo.GetByFilterList(a => a.AktifMi == true && a.DonemID == d.DonemID && a.OgretmenID == OgretmenID).OrderByDescending(a => a.YoklamaID).ToList();

            if (Sinif != 0 && !String.IsNullOrEmpty(Sube) && DersID != 0 && DersGrupID != 0)
            {
                Ogretmenler ogr = ogretmenrepo.Get(OgretmenID);
                model.OgrenciListe = ogrencirepo.GetByFilterList(a => a.Sinif == Sinif && a.Sube == Sube && a.AktifMi == true && a.OkulID == ogr.OkulID).OrderBy(a => a.OgrenciNo).ToList();
                model.DersGrupID = DersGrupID;
                model.DersID = DersID;
                model.Sinif = Sinif;
                model.Sube = Sube;
                model.DersAdi = dersrepo.Get(DersID).DersAdi;
                model.DersGrupAdi = dersgruprepo.Get(DersGrupID).DersGrupAdi;
                model.FiltreUygulandıMı = true;
                model.Tarih = DateTime.Now;
            }

            return View(model);
        }

        [HttpPost]
        [LogFolder.OgretmenLog]
        public JsonResult YoklamaKaydet(YoklamaViewModel model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Donemler d = donemrepo.GetByFilter(a => a.AktifMi == true);
                Ogretmenler ogretmen = ogretmenrepo.Get(Convert.ToInt32(Session["OgretmenID"].ToString()));
                List<Yoklamalar> yoklist = yoklamarepo.GetByFilterList(a => a.AktifMi == true && a.DersGrupID == model.DersGrupID && a.DonemID == d.DonemID && a.OkulID == ogretmen.OkulID && a.Sinif == model.Sinif && a.Sube == model.Sube).OrderByDescending(a=>a.YoklamaID).ToList();
                Yoklamalar varmi = (from i in yoklist
                                    where Convert.ToDateTime(i.Tarih).Date == Convert.ToDateTime(model.Tarih).Date
                                    select i).FirstOrDefault();
                
                bool durum = false;
                if (varmi != null)
                {
                    DateTime tarih1 = (DateTime)varmi.Tarih;
                    DateTime tarih2 = (DateTime)model.Tarih;
                    if (tarih1.Date == tarih2.Date)
                    { durum = true; }
                    else
                    { durum = false; }
                }
                if (durum == false)
                {
                    Yoklamalar y = new Yoklamalar();
                    string[] ogridliste = model.OgrenciIDListe;
                    if (model.OgrenciIDListe != null)
                    {
                        for (int i = 0; i < ogridliste.Length; i++)
                        {
                            y.OgrenciIDListe += ogridliste[i];
                            if (i + 1 < ogridliste.Length)
                            {
                                y.OgrenciIDListe += ",";
                            }
                        }
                    }
                    y.AktifMi = true;
                    y.DersGrupID = model.DersGrupID;
                    y.DersID = model.DersID;
                    y.DonemID = d.DonemID;
                    y.OgretmenID = ogretmen.OgretmenID;
                    y.OkulID = ogretmen.OkulID;
                    y.Sinif = model.Sinif;
                    y.Sube = model.Sube;
                    y.Tarih = model.Tarih;
                    yoklamarepo.Add(y);
                    jmodel.IsSuccess = true;
                    jmodel.UserMessage = "Yoklama alınmıştır.";
                }
                else
                {
                    jmodel.IsSuccess = false;
                    jmodel.UserMessage = varmi.Tarih + " tarihinde ," + varmi.Sinif + "/" + varmi.Sube + " sınıfı " + varmi.Dersler.DersAdi + " dersine ait " + varmi.DersGruplari.DersGrupAdi + "  saati için zaten yoklama alınmış.";
                }
            }
            catch (Exception)
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Yoklama alırken bir sorunla karşılaştık. Lütfen daha sonra tekrar deneyiniz.";
            }

            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _YoklamaFiltreModal()
        {
            int OgretmenID = Convert.ToInt32(Session["OgretmenID"]);
            SinifDersOgrenciListView model = new SinifDersOgrenciListView();
            model.SinifGrup = (from i in atanandersrepo.GetByFilterList(a => a.OgretmenID == OgretmenID && a.AktifMi == true).ToList()
                               orderby i.Sinif
                               group i by i.Sinif into g
                               select new SelectListItem
                               {
                                   Text = g.Key.ToString(),
                                   Value = g.Key.ToString()
                               }).ToList();

            ViewData["DersSaatleri"] = from i in dersgruprepo.GetAll()
                                       select new SelectListItem
                                       {
                                           Value = i.DersGrupID.ToString(),
                                           Text = i.DersGrupAdi
                                       };
            model.Sinif = 0;
            model.Sube = "0";
            model.DersGrupID = 0;
            model.DersID = 0;
            return PartialView("_YoklamaFiltreModal", model);
        }

        [LogFolder.OgretmenLog]
        public ActionResult Profil()
        {

OD.UI/Views/Ogretmen/Index.cshtml
@{
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

OD.UI/Views/Ogretmen/Profil.cshtml
@model OD.Model.Ogretmenler
@using OD.UI.Utils
@{
    Fonksiyon f = new Fonksiyon();
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

<div class="row mt-5">
    <div class="col-sm-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h6 class="panel-title txt-dark">Öğretmen Bilgileri</h6>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-wrapper collapse in">
                <div class="panel-body task-panel">
                    <div class="list-group mb-0">
                        <a href="#" class="list-group-item">
                            <span class="pull-right">@Model.AdSoyad</span>
                            Ad Soyad :
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="pull-right">@f.Decrypt(Model.KullaniciAdi)</span>
                            Kullanıcı Adı :
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="pull-right">@Convert.ToDateTime(Model.KayitTarihi).ToLongDateString()</span>
                            Kayıt Tarihi :
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="pull-right">@Model.Donemler.DonemAdi</span>
                            Dönem :
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="pull-right">@Model.Okullar.Adi</span>
                            Okul Adı :
                        </a>
                        <div class="mt-20">
                            <a href="#" id="guncelle" class="btn btn-success">Bilgilerimi Güncelle</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="guncelle-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Güncelle</h4>
            </div>
            <div class="modal-body" id="OgretmenGuncelle">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).on("click", "#guncelle", function () {
            var url = "/Ogretmen/_OgretmenBilgileri";

            $("#OgretmenGuncelle").load(url, function () {
                $("#guncelle-modal").modal("show");
            })
        });
    </script>
    } 

OD.UI/Views/Ogretmen/YoklamaAl.cshtml
@model OD.UI.ViewModel.SinifDersOgrenciListView
@using OD.Bll.Concrete;
@{
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

<div class="row mt-3">
    <div class="col-sm-3">
        <a href="#" class="btn btn-primary" id="btnyoklamafiltre"><i class="fa fa-plus"></i> Yeni Yoklama Al</a>
    </div>
</div>
@if (Model.FiltreUygulandıMı == true)
{
    <div class="row mt-5">
        <div class="col-sm-4">
            <div class="panel panel-default card-view">
                <div class="panel-heading">
                    <div class="pull-left">
                        <h6 class="panel-title txt-dark">Bilgiler</h6>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-wrapper collapse in">
                    <div class="panel-body task-panel">
                        <div class="list-group mb-0">
                            <a href="#" class="list-group-item">
                                <span class="pull-right">@Model.Sinif</span>
                                Sınıf :
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="pull-right">@Model.Sube</span>
                                Şube :
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="pull-right">@Model.DersAdi</span>
                                Ders Adı :
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="pull-right">@Model.DersGrupAdi</span>
                                Ders Saati :
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="pull-right">@Model.Tarih.ToLongDateString()</span>
                                Tarih :
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="panel panel-default card-view">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        @using (Ajax.BeginForm("YoklamaKaydet", "Ogretmen", new AjaxOptions { OnSuccess = "YoklamaKaydetResult", HttpMethod = "POST" }, new { @class = "form-horizontal" }))
                        {
                            @Html.HiddenFor(m => m.DersGrupID)
                            @Html.HiddenFor(m => m.DersID)
                            @Html.HiddenFor(m => m.Sinif)
                            @Html.HiddenFor(m => m.Sube)
                            @Html.HiddenFor(m => m.Tarih)
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr class="bg-light">
                                        <th>Seç</th>
                                        <th>Öğrenci No</th>
                                        <th>Adı</th>
                                        <th>Soyadı</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.OgrenciListe)
                                    {
                                        <tr>
                                            <td align="center"><input type="checkbox" id="check" name="OgrenciIDListe" value="@item.OgrenciID" data-id="@item.OgrenciNo" data-ad="@item.Adi @item.Soyadi" /></td>
                                            <td>@item.OgrenciNo</td>
                                            <td>@item.Adi</td>
                                            <td>@item.Soyadi</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <div class="col-md-12"><input type="submit" class="btn btn-success" value="Yoklamayı Kaydet" /></div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row mt-5">
        <div class="col-sm-12">
            <div class="panel panel-default card-view">
                <div class="panel-heading">
                    <div class="pull-left">
                        <h6 class="panel-title txt-dark">Yoklama Listesi</h6>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        <table id="datable_1" class="table table-hover display  pb-30">
                            <thead>
                                <tr class="bg-light">
                                    <th>ID</th>
                                    <th>Tarih</th>
                                    <th>Ders Adı</th>
                                    <th>Ders Saati</th>
                                    <th>Sınıf</th>
                                    <th>Şube</th>
                                    <th>Öğrenci Bilgileri</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in (List<OD.Model.Yoklamalar>)ViewData["YoklamaListe"])
                                {
                                    <tr>
                                        <td>@item.YoklamaID</td>
                                        <td>@item.Tarih</td>
                                        <td>@item.Dersler.DersAdi</td>
                                        <td>@item.DersGruplari.DersGrupAdi</td>
                                        <td>@item.Sinif</td>
                                        <td>@item.Sube</td>
                                        <td>
                                            @{
                                                if (item.OgrenciIDListe != null)
                                                {
                                                    string[] liste = item.OgrenciIDListe.Split(',');
                                                    OgrenciRepository ogrrepo = new OgrenciRepository();
                                                    OD.Model.Ogrenciler ogr = new OD.Model.Ogrenciler();
                                                    for (int i = 0; i < liste.Length; i++)
                                                    {
                                                        int id = Convert.ToInt32(liste[i]);
                                                        ogr = ogrrepo.Get(id);
                                                        <span>@ogr.OgrenciNo - @ogr.Adi @ogr.Soyadi</span><br />
                                                    }
                                                }
                                                else
                                                {
                                                    <span class="bg-success">Sınıfta gelmeyen öğrenci yoktur.</span>
                                                }
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="modal fade" id="filtre-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Sınıf Seçiniz</h4>
            </div>
            <div class="modal-body" id="YoklamaFiltre">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/DataTable_Turkish.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#datable_1').DataTable();

            // Sort by columns 1 and 2 and redraw
            table
                .order([0, 'desc'])
                .draw();
        });

        $("input[type='checkbox']").change(function () {
            if (this.checked) {
                var id = $(this).data("id");
                var adsoyad = $(this).data("ad");
                toastr.success(id + "-" + adsoyad + " öğrenci seçildi.");
            }
        });

        $(document).on("click", "#btnyoklamafiltre", function () {
            var url = "/Ogretmen/_YoklamaFiltreModal";

            $("#YoklamaFiltre").load(url, function () {
                $("#filtre-modal").modal("show");
            })
        });
        function YoklamaKaydetResult(result) {
            if (result.IsSuccess == true) {

                var dialog = bootbox.dialog({
                    title: 'BAŞARILI!',
                    message: "<p>" + result.UserMessage + "</p>",
                    buttons: {
                        ok: {
                            label: "Tamam",
                            className: 'btn-success',
                            callback: function () {
                                window.location.href = "/Ogretmen/YoklamaAl";
                            }
                        }
                    }
                });
            }
            else {
                var dialog = bootbox.dialog({
                    title: 'UYARI!',
                    message: "<p>" + result.UserMessage + "</p>",
                    buttons: {
                        ok: {
                            label: "Tamam",
                            className: 'btn-danger',
                            callback: function () {
                                window.location.href = "/Ogretmen/YoklamaAl";
                            }
                        }
                    }
                });
            }
        };
    </script>
}

OD.UI/Views/Ogretmen/_OgretmenBilgileri.cshtml
@model OD.Model.Ogretmenler
@using OD.UI.Utils
@{ 
    Fonksiyon f = new Fonksiyon();
}

@using (Ajax.BeginForm("OgretmenGuncelle", "Ogretmen", new AjaxOptions { OnSuccess = "GuncelleSonuc", HttpMethod = "POST" }, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(m => m.OgretmenID)
    <div class="form-group">
        <label class="col-sm-3 control-label">Ad Soyad</label>
        <div class="col-sm-9">
            <input class="form-control" name="AdSoyad" id="adsoyad" type="text" value="@Model.AdSoyad" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Kullanıcı Adı</label>
        <div class="col-sm-9">
            <input class="form-control" name="KullaniciAdi" id="kullaniciadi" type="text" value="@f.Decrypt(Model.KullaniciAdi)" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Şifre</label>
        <div class="col-sm-9">
            <input class="form-control" name="Sifre" id="sifre" type="password" value="@f.Decrypt(Model.Sifre)" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Dönem Adı</label>
        <div class="col-sm-9">
            <input class="form-control" name="Donem" id="donem" type="text" value="@Model.Donemler.DonemAdi" disabled>
        </div>
    </div>
    <div class="form-group mb-0">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-success">Güncelle</button>
        </div>
    </div>
}
<script>
    function GuncelleSonuc(res) {
        if (res.IsSuccess == true) {
            //$("#modal-fadein").modal("hide");
            //var dialog = bootbox.dialog({
            //    title: 'SİSTEM MESAJI!',
            //    message: "<p>" + res.UserMessage + "</p>",
            //    buttons: {
            //        ok: {
            //            label: "Tamam",
            //            className: 'btn-success',
            //            callback: function () {
            //                window.location.href = '/Okul/Dersler';
            //            }
            //        }
            //    }
            //});
            window.location.href = '/Ogretmen/Profil';
        }
        else {
            toastr.error(res.UserMessage);
        }
    }
</script>

OD.UI/Views/Ogretmen/_YoklamaFiltreModal.cshtml
@model OD.UI.ViewModel.SinifDersOgrenciListView
@using (Html.BeginForm("YoklamaAl","Ogretmen"))
{
    <div class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-3 control-label">Sınıf Seçiniz</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(m => Model.Sinif, new SelectList(Model.SinifGrup, "Value", "Text"), "Sınıf Seçiniz", htmlAttributes: new { @class = "form-control", @tabindex = "-1" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">Şube Seçiniz</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(m => Model.Sube, Model.SubeGrup, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">Ders Seçiniz</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(m => Model.DersID, Model.DersListe, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">Ders Saati Seçiniz</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(m => Model.DersGrupID, (IEnumerable<SelectListItem>)ViewData["DersSaatleri"], "Ders Saati Seçiniz", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <input type="submit" value="Listele" class="btn btn-success col-md-12" />
            </div>
        </div>
    </div>
}

<script>

    $("#Sinif").change(function () {
        var id = $(this).val();
        var SubeListe = $("#Sube");
        SubeListe.empty();
        $.ajax({
            url: '/Ogretmen/SinifSubeFiltre/',
            type: 'POST',
            dataType: 'json',
            data: { 'id': id },
            success: function (data) {
                SubeListe.append('<option value=0>Şube Seçiniz</option>');
                $.each(data, function (index, option) {
                    SubeListe.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                });
            }
        });
    });

    $("#Sube").change(function () {
        var sube = $(this).val();
        var sinif = $("#Sinif").val();
        var DersListe = $("#DersID");
        DersListe.empty();
        $.ajax({
            url: '/Ogretmen/SinifDersFiltre/',
            type: 'POST',
            dataType: 'json',
            data: { 'sinif': sinif, 'sube': sube },
            success: function (data) {
                DersListe.append('<option value=0>Ders Seçiniz</option>');
                $.each(data, function (index, option) {
                    DersListe.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                });
            }
        });
    });
</script>