OD.UI/Controllers/AdminController.cs
using OD.Bll.Concrete;
using OD.Model;
using OD.UI.LogFolder;
using OD.UI.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace OD.UI.Controllers
{
    public class AdminController : BaseController.BaseController
    {
        Fonksiyon f = new Fonksiyon();

        AdminRepository adminrepo = new AdminRepository();
        TaleplerRepository taleprepo = new TaleplerRepository();
        DonemlerRepository donemrepo = new DonemlerRepository();
        OkulRepository okulrepo = new OkulRepository();
        AdminLogRepository adminlogrepo = new AdminLogRepository();
        OgretmenLogRepository ogretmenlogrepo = new OgretmenLogRepository();
        OkulLogRepository okullogrepo = new OkulLogRepository();

        //[LogFolder.AdminLog]
        public ActionResult Index()
        {
            return View();
        }

        //[LogFolder.AdminLog]
        public ActionResult Profil()
        {
            return View();
        }

        //[LogFolder.AdminLog]
        [HttpPost]
        public JsonResult ProfilGuncelle(AdminTBL model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                int id = Convert.ToInt32(Session["AdminID"]);
                AdminTBL admin = adminrepo.Get(id);
                admin.KullaniciAdi = f.Encrypt(model.KullaniciAdi);
                admin.Sifre = f.Encrypt(model.Sifre);
                adminrepo.Update(admin);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Güncelleme işlemi başarılı bir şekilde gerçekleştirildi.";
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Güncelleme işlemi sırasında bir hata oluştu.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CikisYap()
        {
            Session.Remove("AdminID");
            return RedirectToAction("AdminGirisi", "Home");
        }

        //[LogFolder.AdminLog]
        public ActionResult AktifTalepler()
        {
            List<Talepler> aktiftalep = taleprepo.GetByFilterList(a => a.AktifMi == true);
            return View(aktiftalep);
        }

        //[LogFolder.AdminLog]
        public ActionResult PasifTalepler()
        {
            List<Talepler> pasiftalep = taleprepo.GetByFilterList(a => a.AktifMi == false);
            return View(pasiftalep);
        }

        //[LogFolder.AdminLog]
        public ActionResult Donemler()
        {
            List<Donemler> donemliste = donemrepo.GetAll().OrderByDescending(a => a.DonemID).ToList();
            return View(donemliste);
        }

        //[LogFolder.AdminLog]
        public JsonResult DonemEkle(Donemler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                foreach (var item in donemrepo.GetAll())
                {
                    item.AktifMi = false;
                    donemrepo.Update(item);
                }
                foreach (var i in okulrepo.GetByFilterList(a=>a.AktifMi==true&& a.BitisTarihi>DateTime.Now))
                {
                    i.OgrenciListeYuklediMi = false;
                    okulrepo.Update(i);
                }
                model.Baslama = Convert.ToDateTime(model.Baslama);
                model.Bitis = Convert.ToDateTime(model.Bitis);
                model.AktifMi = true;
                donemrepo.Add(model);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Dönem ekleme işlemi başarılı bir şekilde gerçekleştirildi.";
        }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Dönem ekleme işlemi sırasında bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _DonemGuncelleme(int id)
        {
            Donemler donem = donemrepo.Get(id);
            return PartialView("_DonemGuncelle", donem);
        }

        //[LogFolder.AdminLog]
        [HttpPost]
        public JsonResult DonemGuncelleislem(Donemler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Donemler donem = donemrepo.Get(model.DonemID);
                donem.Baslama = Convert.ToDateTime(model.Baslama);
                donem.Bitis = Convert.ToDateTime(model.Bitis);
                donem.DonemAdi = model.DonemAdi;
                donemrepo.Update(donem);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Dönem Güncelleme işlemi başarılı bir şekilde yapıldı.";
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Güncelleme işlemi sırasında bir hata oluştu.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _Talepislem(int id)
        {
            Talepler talep = taleprepo.Get(id);
            return PartialView("_Talepislem", talep);
        }

        //[LogFolder.AdminLog]
        [HttpPost]
        public JsonResult TalepislemYap(int TalepID, int sure)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Talepler talep = taleprepo.Get(TalepID);
                Okullar okul = okulrepo.Get((int)talep.OkulID);
                okul.BaslangicTarihi = DateTime.Now;
                okul.BitisTarihi = DateTime.Now.Date.AddMonths(sure);

                okul.AktifMi = true;
                talep.AktifMi = false;

                okulrepo.Update(okul);
                taleprepo.Update(talep);

                jmodel.IsSuccess = true;
                jmodel.UserMessage = "İşlem başarılı bir şekilde gerçekleştirildi.";
            }
            catch (Exception)
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Güncelleme işlemi sırasında bir hata oluştu.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _OkulDetay(int id)
        {
            Talepler talep = taleprepo.Get(id);
            Okullar okul = okulrepo.Get((int)talep.OkulID);
            return PartialView("_OkulDetay", okul);
        }

        //[LogFolder.AdminLog]
        public ActionResult OkulListesi()
        {
            return View(okulrepo.GetAll().OrderByDescending(a => a.OkulID).ToList());
        }

        //[LogFolder.AdminLog]
        public ActionResult AdminLog()
        {
            return View(adminlogrepo.GetAll());
        }

        //[LogFolder.AdminLog]
        public ActionResult OgretmenLog()
        {
            return View(ogretmenlogrepo.GetAll());
        }

        //[LogFolder.AdminLog]
        public ActionResult OkulLog()
        {
            return View(okullogrepo.GetAll());
        }
    }
}

OD.UI/Controllers/OkulController.cs
using OD.Bll.Concrete;
using OD.Model;
using OD.UI.Report;
using OD.UI.Utils;
using OD.UI.ViewModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExcelDataReader;
using System.IO;

namespace OD.UI.Controllers
{
    public class OkulController : BaseController.BaseController
    {
        OgretmenRepository ogretmenrepo = new OgretmenRepository();
        OgrenciRepository ogrencirepo = new OgrenciRepository();
        DerslerRepository dersrepo = new DerslerRepository();
        AtananDerslerRepository atanandersrepo = new AtananDerslerRepository();
        DonemlerRepository donemrepo = new DonemlerRepository();
        OkulRepository okulrepo = new OkulRepository();
        YoklamaRepository yoklamarepo = new YoklamaRepository();
        DersGruplariRepository dersgruprepo = new DersGruplariRepository();
        OgretmenLogRepository ogretmenlogrepo = new OgretmenLogRepository();
        Fonksiyon f = new Fonksiyon();

        [LogFolder.OkulLog]
        public ActionResult Index()
        {
            int id = Convert.ToInt32(Session["OkulID"]);
            ViewBag.OgrenciSayisi = ogrencirepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id).Count();
            ViewBag.OgretmenSayisi = ogretmenrepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id).Count();
            ViewBag.DersSayisi = dersrepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id).Count();
            List<Yoklamalar> BugunYoklama = (from i in yoklamarepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id)
                                             where Convert.ToDateTime(i.Tarih).Date == DateTime.Now.Date
                                             orderby i.Sinif, i.Sube, i.DersGrupID
                                             select i).ToList();
            ViewBag.BugunYoklamaSayisi = BugunYoklama.Count();
            ViewBag.ToplamYoklamaSayisi = yoklamarepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id).Count();
            List<OgretmenLogViewModel> OgretmenLogListe = (from i in ogretmenlogrepo.GetByFilterList(a => a.Ogretmenler.OkulID == id)
                                                           where Convert.ToDateTime(i.Date).Date == DateTime.Now.Date
                                                           group i by i.OgretmenID
                                                  into g
                                                           select new OgretmenLogViewModel
                                                           {
                                                               OgretmenID = Convert.ToInt32(g.Key.ToString()),
                                                               AdSoyad = g.Select(n => n.Ogretmenler.AdSoyad).FirstOrDefault(),
                                                               Tarih = g.Select(n => n.Date).FirstOrDefault().ToString(),
                                                           }).ToList();
            ViewData["OgretmenLogListe"] = OgretmenLogListe;
            return View(BugunYoklama);
        }

        public ActionResult CikisYap()
        {
            Session.Remove("OkulID");
            return RedirectToAction("OkulGirisi", "Home");
        }

        [LogFolder.OkulLog]
        public ActionResult Ogretmenler()
        {
            ViewBag.Donem = donemrepo.GetByFilter(a => a.AktifMi == true).DonemAdi;
            int id = Convert.ToInt32(Session["OkulID"]);
            List<Ogretmenler> ogretmenler = ogretmenrepo.GetByFilterList(a => a.OkulID == id && a.AktifMi == true).OrderByDescending(a => a.OgretmenID).ToList();
            return View(ogretmenler);
        }

        [HttpPost]
        [LogFolder.OkulLog]
        public JsonResult OgretmenEkle(Ogretmenler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                if (f.OgretmenKullaniciAdiVarMi(f.Encrypt(model.KullaniciAdi)) == false)
                {
                    jmodel.IsSuccess = false;
                    jmodel.UserMessage = "Aynı kullanıcı adına sahip başka bir öğretmen var. Lütfen kullanıcı adınızı değiştiriniz.";
                }
                else
                {
                    model.KayitTarihi = DateTime.Now;
                    model.AktifMi = true;
                    model.OkulID = Convert.ToInt32(Session["OkulID"]);
                    model.KullaniciAdi = f.Encrypt(model.KullaniciAdi);
                    model.Sifre = f.Encrypt(model.Sifre);
                    model.DonemID = donemrepo.GetByFilter(a => a.AktifMi == true).DonemID;
                    ogretmenrepo.Add(model);
                    jmodel.IsSuccess = true;
                    jmodel.UserMessage = model.AdSoyad + " isimli öğretmene ait bilgiler başarılı bir şekilde eklendi.";
                }
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Öğretmen bilgilerini eklerken bir sorunla karşılaştık. Lütfen daha sonra tekrar deneyiniz.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        [LogFolder.OkulLog]
        public ActionResult Dersler()
        {
            ViewBag.Donem = donemrepo.GetByFilter(a => a.AktifMi == true).DonemAdi;
            int id = Convert.ToInt32(Session["OkulID"]);
            List<Dersler> dersler = dersrepo.GetByFilterList(a => a.AktifMi == true && a.OkulID == id).OrderByDescending(a => a.DersAdi).ToList();
            return View(dersler);
        }

        [HttpPost]
        [LogFolder.OkulLog]
        public JsonResult DersEkle(Dersler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {

                model.DonemID = donemrepo.GetByFilter(a => a.AktifMi == true).DonemID;
                model.AktifMi = true;
                model.OkulID = Convert.ToInt32(Session["OkulID"]);
                dersrepo.Add(model);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Ders Ekleme işlemi başarılı.";
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Ders ekleme işlemi sırasında bir sorunla karşılaştık. Lütfen daha sonra tekrar deneyiniz.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [LogFolder.OkulLog]
        public JsonResult DersSil(int id)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Dersler ders = dersrepo.Get(id);
                ders.AktifMi = false;
                dersrepo.Update(ders);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Ders Silme işlemi başarılı.";
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Ders silme işlemi sırasında bir sorunla karşılaştık. Lütfen daha sonra tekrar deneyiniz.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _DersGuncelle(int id)
        {
            Dersler ders = dersrepo.Get(id);
            return PartialView("_DersGuncelle", ders);
        }

        [HttpPost]
        [LogFolder.OkulLog]
        public JsonResult DersGuncelleislem(Dersler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Dersler ders = dersrepo.Get(model.DersID);
                ders.DersAdi = model.DersAdi;
                dersrepo.Update(ders);
                jmodel.IsSuccess = true;
                jmodel.UserMessage = "Ders güncelleme işlemi başarılı bir şekilde gerçekleştirildi.";
            }
            catch
            {
                jmodel.IsSuccess = false;
                jmodel.UserMessage = "Ders güncelleme işlemi sırasında bir sorunla karşılaştık. Lütfen daha sonra tekrar deneyiniz.";
            }
            return Json(jmodel, JsonRequestBehavior.AllowGet);
        }

        [LogFolder.OkulLog]
        public ActionResult _OgretmenDetay(int id)
        {
            Ogretmenler ogretmen = ogretmenrepo.Get(id);
            //ViewData["AtananDersler"] = atanandersrepo.GetByFilterList(a => a.OgretmenID == ogretmen.OgretmenID).OrderBy(a => a.Dersler.DersAdi).ToList();
            return PartialView("_OgretmenDetay", ogretmen);
        }

        [LogFolder.OkulLog]
        public ActionResult _OgretmenGuncelle(int id)
        {
            ViewBag.Donem = donemrepo.GetByFilter(a => a.AktifMi == true).DonemAdi;
            Ogretmenler ogretmen = ogretmenrepo.Get(id);
            return PartialView("_OgretmenGuncelle", ogretmen);
        }

        [LogFolder.OkulLog]
        [HttpPost]
        public JsonResult OgretmenGuncelleislem(Ogretmenler model)
        {
            JsonResultModel jmodel = new JsonResultModel();
            try
            {
                Ogretmenler o = ogretmenrepo.GetByFilter(a => a.KullaniciAdi == f.Decrypt(model.KullaniciAdi));
                if (o != null)
                {
                    Ogretmenler ogr = ogretmenrepo.Get(model.OgretmenID);
                    ogr.AdSoyad = model.AdSoyad;
                    ogr.KullaniciAdi = f.Encrypt(model.KullaniciAdi);
                    ogr.Sifre = f.Encrypt(model.Sifre);
                    ogretmenrepo.Update(ogr);
                    jmodel.IsSuccess = true;
                    jmodel.UserMessage = "Öğretmen bilgileri başarılı bir şekilde güncellendi.";
                }
                else
                {
                    jmodel.IsSuccess = false;
                    jmodel.UserMessage = model.KullaniciAdi + " kullanıcı adına sahip başka bir öğretmenimiz zaten var. Lütfen başka bir kullanıcı adı belirleyiniz.";
                }
            }
            catch
            {

OD.UI/Views/Okul/BugunYoklama.cshtml
@model OD.UI.ViewModel.SinifSubeDersGrupView
@using OD.Bll.Concrete;
@using OD.UI.Utils;
@{
    Layout = "~/Views/Shared/_OkulLayout.cshtml";
    int OkulID = Convert.ToInt32(Session["OkulID"]);
    List<OD.UI.ViewModel.YoklamaViewModel> Yoklamaliste = ViewData["Yoklama"] as List<OD.UI.ViewModel.YoklamaViewModel>;
    ViewBag.Title = ViewBag.Sinif + "/" + ViewBag.Sube + " Günlük Yoklama Listesi - Tarih : " + DateTime.Now.ToLongDateString() + " - Saat : " + DateTime.Now.ToShortTimeString();
    Fonksiyon f = new Fonksiyon();
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default card-view">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">
                                <div class="form-wrap">
                                    @using (Html.BeginForm("BugunYoklama", "Okul"))
                                    {
                                        @Html.Hidden("OkulID", OkulID)
                                        <div class="row">
                                            <div class="col-md-4">
                                                @Html.DropDownListFor(m => m.Sinif, new SelectList(Model.SinifGrup, "Value", "Text"), "Sınıf Seçiniz", htmlAttributes: new { @class = "form-control", @tabindex = "-1" })
                                            </div>
                                            <div class="col-md-4">
                                                @Html.DropDownListFor(model => model.Sube, Model.SubeGrup, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                            <div class="col-md-4">
                                                <button type="submit" class="btn btn-primary col-md-12">Listele</button>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div><!-- .widget-body -->
                </div>
            </div><!-- .widget -->
        </div><!-- END column -->
    </div><!-- .row -->
</div>
@if (Yoklamaliste != null && Yoklamaliste.Count != 0 && Convert.ToBoolean(ViewBag.SecimVarmi) == true)
{
    <div class="container">
        <a href="@Url.Action("YoklamaPDFAktar", "Okul", new { Sinif =ViewBag.Sinif,Sube=ViewBag.Sube,title=ViewBag.Title,Tarih=DateTime.Now.Date})" class="btn btn-primary" target="_blank">PDF Aktar</a>
        @*<a href="#" id="guncelle" data-sinif="@ViewBag.Sinif" data-sube="@ViewBag.Sube" class="btn btn-success">Listeyi Güncelle</a>*@
        <div class="row mt-5" id="YoklamaListeTablo">
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="text-center">
                            <h6 class="panel-title txt-primary">@ViewBag.Title</h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table id="asd" class="table table-hover display  pb-30">
                                        <thead>
                                            <tr>
                                                <th>Öğrenci No</th>
                                                <th>Adı</th>
                                                <th>Soyadı</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Yoklamaliste)
                                            {
                                                <tr>
                                                    <td class="bg-light text-danger" colspan="3">@f.DersSaatiGetir((int)item.DersGrupID).DersGrupAdi - @f.DersGetir((int)item.DersID).DersAdi - @f.OgretmenGetir((int)item.OgretmenID).AdSoyad <label>@Html.ActionLink("Değişiklik Yap", "YoklamaGuncelle", "Okul", new { YoklamaID = item.YoklamaID }, new { @class = "btn btn-default btn-xs" })</label></td>
                                                </tr>

                                                if (item.OgrenciIDListe != null)
                                                {
                                                    for (int i = 0; i < item.OgrenciIDListe.Length; i++)
                                                    {
                                                        <tr>
                                                            <td>@f.OgrenciGetir(Convert.ToInt32(item.OgrenciIDListe[i])).OgrenciNo</td>
                                                            <td>@f.OgrenciGetir(Convert.ToInt32(item.OgrenciIDListe[i])).Adi</td>
                                                            <td>@f.OgrenciGetir(Convert.ToInt32(item.OgrenciIDListe[i])).Soyadi</td>
                                                        </tr>
                                                    }
                                                }
                                                else
                                                {
                                                    <tr><td class="text-success" colspan="3">Sınıfta gelmeyen öğrenci yoktur.</td></tr>
                                                }
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else if ((Yoklamaliste == null || Yoklamaliste.Count == 0) && Convert.ToBoolean(ViewBag.SecimVarmi) == true)
{
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="text-center">
                            <h6 class="panel-title txt-primary">@ViewBag.Title</h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="text-center text-danger">
                                    Seçilen sınıf ve şube için bugün yoklama alınmamış.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="modal-fadein" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Yoklama Güncelle</h4>
            </div>
            <div class="modal-body" id="YoklamaGuncelle">

            </div>
        </div>
    </div>
</div>


@section Scripts{

    <script>
        $("#Sinif").change(function () {
            var id = $(this).val();
            var SubeListe = $("#Sube");
            SubeListe.empty();
            $.ajax({
                url: '/Okul/SinifSubeFiltre/',
                type: 'POST',
                dataType: 'json',
                data: { 'id': id },
                success: function (data) {
                    SubeListe.append('<option value=0>Şube Seçiniz</option>');
                    $.each(data, function (index, option) {
                        SubeListe.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                    });
                }
            });
        });

        $(document).on("click", "#guncelle", function () {
            var sinif = $(this).data("sinif");
            var sube = $(this).data("sube");
            var url = "/Okul/_YoklamaGuncelle/Sinif=" + sinif + "&Sube=" + sube;

            $("#YoklamaGuncelle").load(url, function () {
                $("#modal-fadein").modal("show");
            })
        });
    </script>
}

OD.UI/Views/Okul/_AtananDerslerView.cshtml
@model OD.Model.Ogretmenler
@using OD.Model
@using OD.Bll.Concrete
@{
    AtananDerslerRepository atanandersrepo = new AtananDerslerRepository();
    DonemlerRepository donemrepo = new DonemlerRepository();
    Donemler donem = donemrepo.GetByFilter(a => a.AktifMi == true);
    List<AtananDersler> dersler = atanandersrepo.GetByFilterList(a => a.OgretmenID == Model.OgretmenID && a.AktifMi == true && a.DonemID == donem.DonemID);
    var liste = from k in dersler
                orderby k.Sinif, k.Sube, k.Dersler.DersAdi
                select new
                {
                    ID = k.AtananDersID,
                    Sinif = k.Sinif,
                    Sube = k.Sube.ToUpper(),
                    DersAdi = k.Dersler.DersAdi
                };
}
@if (liste == null || liste.Count()==0)
{
    <span class="text-danger"><b>Öğretmene atanmış ders bulunmamaktadır.</b></span>
}
else
{
    <span class="text-primary">Toplam Ders Atama Sayısı : @liste.Count()</span>
    <ul>
        @foreach (var item in liste)
        {
            <li>@item.Sinif - @item.Sube - @item.DersAdi</li>
        }
    </ul>
}

OD.UI/Views/Okul/_DersGuncelle.cshtml
@model OD.Model.Dersler

<div class="row">
    <div class="col-md-12">
        @using (Ajax.BeginForm("DersGuncelleislem", "Admin", new AjaxOptions { OnSuccess = "Sonuc", HttpMethod = "POST" }, new { @class = "form-horizontal" }))
        {
            @Html.HiddenFor(m => m.DersID)
            <div class="form-group">
                <label for="#" class="col-sm-3 control-label">Ders Adı : </label>
                <div class="col-sm-9">
                    <input class="form-control" name="DersAdi" id="dersadi" type="text" value="@Model.DersAdi" required>
                </div>
            </div>
            <div class="form-group">
                <label for="#" class="col-sm-3 control-label">Sınıf Düzeyi : </label>
                <div class="col-sm-9">
                    <input class="form-control" name="SinifDuzey" id="sinifduzey" type="number" value="@Model.SinifDuzey" required>
                </div>
            </div>
            <div class="form-group mb-0">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-success" id="btndersguncelle">Güncelle</button>
                </div>
            </div>
        }
    </div>
</div>

<script>
    function Sonuc(res) {
        if (res.IsSuccess == true) {
            //$("#modal-fadein").modal("hide");
            //var dialog = bootbox.dialog({
            //    title: 'SİSTEM MESAJI!',
            //    message: "<p>" + res.UserMessage + "</p>",
            //    buttons: {
            //        ok: {
            //            label: "Tamam",
            //            className: 'btn-success',
            //            callback: function () {
            //                window.location.href = '/Okul/Dersler';
            //            }
            //        }
            //    }
            //});
            window.location.href = '/Okul/Dersler';
        }
        else {
            toastr.error(res.UserMessage);
        }
    }
</script>